package hibernates;
// Generated 15-ene-2020 22:38:50 by Hibernate Tools 5.4.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 * 
 */
@Entity
@Table(name = "Clientes")

public class ClientePOJO implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "idCliente")
	private Integer idCliente;
	@Column(name = "nombreCliente")
	private String nombre;
	@Column(name="apellidosCliente")
	private String apellidos;
	@Column(name="emailCliente")
	private String email;
	@Column(name="dniCliente")
	private String dni;
	@Column(name="claveCliente")
	private String clave;

	public ClientePOJO() {
	}
	public ClientePOJO(int  idClienteR) {
		this.idCliente = idClienteR;
	}
	public ClientePOJO(int  idClienteR, String apellidosCliente) {
		this.idCliente = idClienteR;
		this.apellidos= apellidosCliente;
	}
	public ClientePOJO(int  idClienteR, String nombreCliente, String apellidosCliente, String emailCliente, String dniCliente,
			String claveCliente) {
		this.idCliente = idClienteR;
		this.nombre = nombreCliente;
		this.apellidos = apellidosCliente;
		this.email = emailCliente;
		this.dni = dniCliente;
		this.clave = claveCliente;
	}
	public ClientePOJO(String nombreCliente, String apellidosCliente, String emailCliente, String dniCliente,
			String claveCliente) {
		this.nombre = nombreCliente;
		this.apellidos = apellidosCliente;
		this.email = emailCliente;
		this.dni = dniCliente;
		this.clave = claveCliente;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombreCliente() {
		return this.nombre;
	}

	public void setNombreCliente(String nombreCliente) {
		this.nombre = nombreCliente;
	}

	public String getApellidosCliente() {
		return this.apellidos;
	}

	public void setApellidosCliente(String apellidosCliente) {
		this.apellidos = apellidosCliente;
	}

	public String getEmailCliente() {
		return this.email;
	}

	public void setEmailCliente(String emailCliente) {
		this.email = emailCliente;
	}

	public String getDniCliente() {
		return this.dni;
	}

	public void setDniCliente(String dniCliente) {
		this.dni = dniCliente;
	}

	public String getClaveCliente() {
		return this.clave;
	}

	public void setClaveCliente(String claveCliente) {
		this.clave = claveCliente;
	}

}
